# Generated by Django 5.2.9 on 2025-12-10 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workouts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='tile',
            new_name='title',
        ),
    ]
